\input texinfo @c -*-texinfo -*-
@c %**start of header
@setfilename emacs-w3m.info
@settitle Emacs-w3m -- an interface program of w3m --
@c %**end of header
@documentlanguage en
@include version.texi
@synindex pg cp
@finalout

@dircategory GNU Emacs Lisp
@direntry
* Emacs-w3m: (emacs-w3m).  An interface program of w3m
@end direntry

@c permissions text appears in an Info file before the first node.
@ifinfo
This file documents emacs-w3m, an interface program of w3m on Emacsen.

Copyright @copyright{} 2000, 2001, 2002 @w{TSUCHIYA Masatoshi}.

This edition is for emacs-w3m version @value{VERSION}.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``A GNU
Manual'', and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License'' in the Emacs manual.

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''

This document is part of a collection distributed under the GNU Free
Documentation License.  If you want to distribute this document
separately from the collection, you can do so by adding a copy of the
license to the document, as described in section 6 of the license.

@end ifinfo

@titlepage
@sp 10
@title Emacs-w3m User's Manual
@subtitle An interface program of w3m on Emacsen
@subtitle for emacs-w3m version @value{VERSION}
@author The emacs-w3m development team
@page

@vskip 0pt plus 1filll
Copyright @copyright{} 2000, 2001, 2002 @w{TSUCHIYA Masatoshi}.

This manual corresponds to emacs-w3m version @value{VERSION}.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``A GNU
Manual'', and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License'' in the Emacs manual.

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''

This document is part of a collection distributed under the GNU Free
Documentation License.  If you want to distribute this document
separately from the collection, you can do so by adding a copy of the
license to the document, as described in section 6 of the license.

@end titlepage

@ifinfo
@node Top
@top Emacs-w3m User's Manual

@flushright
The emacs-w3m development team
@end flushright

This manual corresponds to emacs-w3m version @value{VERSION}.

@end ifinfo

@menu
* Introduction::                Preliminary remarks to emacs-w3m
* Getting Started::             It's so easy to begin to use emacs-w3m
* Index::                       Index

@detailmenu
 --- The Detailed Node Listing ---

Getting Started

* Required Emacs Version::      What version of Emacs can be used?
* You Need w3m::                Using w3m: the reason why emacs-w3m is fast
* Other Requirements::          Things required to run emacs-w3m

@end detailmenu
@end menu

@node Introduction
@chapter Preliminary remarks to emacs-w3m
@cindex Introduction

Our special thanks go to Akinori ITO and a group who have developed the
good w3m program.  W3m is essential to have realized emacs-w3m.  Also
thanks to all for comments, suggestions, and bug fixes.  Even though
there are any problems, all responsibility is in us the emacs-w3m
development team, but there is no warranty as you know.  The emacs-w3m
program was first created by TSUCHIYA Masatoshi in June 2000.

@node Getting Started
@chapter It's so easy to begin to use emacs-w3m
@cindex getting started
@cindex starting up

Emacs-w3m may possibly have already been installed in your system to be
able to use at once.  You may skip this section if you are such a lucky
person; read it over again when you install a new version of emacs-w3m.

@menu
* Required Emacs Version::      What version of Emacs can be used?
* You Need w3m::                Using w3m: the reason why emacs-w3m is fast
* Other Requirements::          Things required to run emacs-w3m
@end menu

@node Required Emacs Version
@section Required Emacs Version
@chapter What version of Emacs can be used?

You can run emacs-w3m in various versions of Emacsen.

@table @samp

@item Emacs 21.x
No additional package is required.

@item Emacs 20.x
No additional package is required.  Furthermore, you can see monochrome
bitmap images inline by using the BITMAP-MULE package.  @xref{Other
Requirements}.

@item XEmacs 21.x
The APEL package and the @samp{gifsicle} program are required
(@pxref{Other Requirements}).  We recommend using the most recent XEmacs
21.4 since that version of XEmacs seems to be most stable.

@item Emacs 19.34 (including Mule 2.3)
The APEL package, the @samp{new custom} package and the
@file{regexp-opt.el} module are required.  @xref{Other Requirements}.

@end table

@node You Need w3m
@section You Need w3m
@chapter Using w3m: the reason why emacs-w3m is fast

Emacs-w3m uses the external w3m command as a back end to retrieve web
contents or a HTML rendering engine.  Since Emacs has been exempted from
those such jobs, we could realize accelerated Emacs web browser and
asynchronous operations.  You must install the latest w3m command.  It
is available in:

@uref{http://prdownloads.sourceforge.net/w3m/}

@node Other Requirements
@section Other Requirements
@chapter Things required to run emacs-w3m


@node Index
@unnumbered Index

@menu
* Concept Index::               Concept Index
* Key Index::                   Key Index
* Variable Index::              Variable Index
* Function Index::              Function Index
@end menu

@node Concept Index
@unnumberedsec Concept Index
@printindex cp

@node Key Index
@unnumberedsec Key Index
@printindex ky

@node Variable Index
@unnumberedsec Variable Index
@printindex vr

@node Function Index
@unnumberedsec Function Index
@printindex fn

@summarycontents
@contents
@bye

@c Local Variables:
@c fill-column: 72
@c End:
