\input texinfo @c -*-texinfo -*- coding: iso-2022-jp -*-
@c %**start of header
@setfilename emacs-w3m-ja.info
@settitle Emacs-w3m -- an interface program of w3m --
@c %**end of header
@documentlanguage ja
@include version.texi
@synindex pg cp
@finalout

@dircategory GNU Emacs Lisp
@direntry
* Emacs-w3m-ja: (emacs-w3m-ja).  An interface program of w3m
@end direntry

@c permissions text appears in an Info file before the first node.
@ifinfo
This file documents emacs-w3m, an interface program of w3m on Emacsen.

このファイルは Emacs で動く w3m のインタフェースである emacs-w3m に関す
る説明書です。

Copyright @copyright{} 2000, 2001, 2002 @w{TSUCHIYA Masatoshi}.

This edition is for emacs-w3m version @value{VERSION}.

この版は emacs-w3m バージョン @value{VERSION} に対応します。

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``A GNU
Manual'', and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License'' in the Emacs manual.

この文書を、フリーソフトウェア財団発行の GNU フリー文書利用許諾契約書
第 1.1 版またはそれ以降の版が定める条件の下で複製、配布、あるいは変更す
ることを許可します。変更不可部分は指定しません。「A GNU Manual」は表表紙
テキスト、以下の (a) は裏表紙テキストです。この利用許諾契約書の複写は
「Emacs manual」の「GNU フリー文書利用許諾契約書」という章に含まれていま
す。

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''

(a) FSF の裏表紙テキスト:「あなたにはこの GNU Manual を GNU ソフトウェア
のように複製したり変更する自由があります。複製はフリーソフトウェア財団に
よって出版されました。(フリーソフトウェア財団は) GNU の開発のために必要
な資金を集めています。」

This document is part of a collection distributed under the GNU Free
Documentation License.  If you want to distribute this document
separately from the collection, you can do so by adding a copy of the
license to the document, as described in section 6 of the license.

この文書は「GNU フリー文書利用許諾契約書」に基づいて配布された収集著作物
の一部です。もしあなたがこの文書を収集著作物から分離して配布したいときは、
契約書の第 6 項に記述されているように、文書に契約書の複写を付加すること
によって、行なうことができます。

@end ifinfo

@titlepage
@sp 10
@title Emacs-w3m ユーザマニュアル
@subtitle An interface program of w3m on Emacsen
@subtitle for emacs-w3m version @value{VERSION}
@author Emacs-w3m 開発チーム
@page

@vskip 0pt plus 1filll
Copyright @copyright{} 2000, 2001, 2002 @w{TSUCHIYA Masatoshi}.

This manual corresponds to emacs-w3m version @value{VERSION}.

このマニュアルは emacs-w3m バージョン @value{VERSION} に対応します。

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``A GNU
Manual'', and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License'' in the Emacs manual.

この文書を、フリーソフトウェア財団発行の GNU フリー文書利用許諾契約書
第 1.1 版またはそれ以降の版が定める条件の下で複製、配布、あるいは変更す
ることを許可します。変更不可部分は指定しません。「A GNU Manual」は表表紙
テキスト、以下の (a) は裏表紙テキストです。この利用許諾契約書の複写は
「Emacs manual」の「GNU フリー文書利用許諾契約書」という章に含まれていま
す。

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''

(a) FSF の裏表紙テキスト:「あなたにはこの GNU Manual を GNU ソフトウェア
のように複製したり変更する自由があります。複製はフリーソフトウェア財団に
よって出版されました。(フリーソフトウェア財団は) GNU の開発のために必要
な資金を集めています。」

This document is part of a collection distributed under the GNU Free
Documentation License.  If you want to distribute this document
separately from the collection, you can do so by adding a copy of the
license to the document, as described in section 6 of the license.

この文書は「GNU フリー文書利用許諾契約書」に基づいて配布された収集著作物
の一部です。もしあなたがこの文書を収集著作物から分離して配布したいときは、
契約書の第 6 項に記述されているように、文書に契約書の複写を付加すること
によって、行なうことができます。

@end titlepage

@ifinfo
@node Top
@top Emacs-w3m ユーザマニュアル

@flushright
Emacs-w3m 開発チーム
@end flushright

この文書は emacs-w3m バージョン @value{VERSION} に対応します。

@end ifinfo

@menu
* Introduction::                はじめに
* Getting Started::             Emacs-w3m を使い始めるのはとっても簡単
* Index::                       索引

@detailmenu
 --- 項目の詳細なリスト ---

Getting Started

* Required Emacs Version::      どんなバージョンの Emacs で使えるの?
* You Need w3m::                w3m を使います: emacs-w3m が速いわけ
* Other Requirements::          emacs-w3m を動作させるのに必要なもの

@end detailmenu
@end menu

@node Introduction
@chapter はじめに
@cindex Introduction

すばらしい w3m プログラムを開発してくれた伊藤彰則さんとそのお仲間に、特
別な感謝を捧げます。W3m は emacs-w3m の実現に不可欠です。さらにコメント、
提案およびバグの修正をしてくれたすべての人々に感謝します。たとえ問題があっ
ても、責任はすべて私たち emacs-w3m 開発チームにあります。もっとも、ご承
知の通り保証はありません。Emacs-w3m は 2000年6月に土屋雅稔によって初めて
作られました。

@node Getting Started
@chapter Emacs-w3m を使い始めるのはとっても簡単
@cindex getting started
@cindex starting up

ひょっとすると、あなたのシステムには emacs-w3m が直ちに使える状態で、す
でにインストールされているかもしれません。そんな幸運な人は、この項を読み
飛ばしても構いません; 新しい emacs-w3m をインストールするときに、もう一
度読み返して下さい。

@menu
* Required Emacs Version::      どんなバージョンの Emacs で使えるの?
* You Need w3m::                w3m を使います: emacs-w3m が速いわけ
* Other Requirements::          emacs-w3m を動作させるのに必要なもの
@end menu

@node Required Emacs Version
@section Required Emacs Version
@chapter どんなバージョンの Emacs で使えるの?

いろいろなバージョンの Emacsen で emacs-w3m を動作させることができます。

@table @samp

@item Emacs 21.x
追加のパッケージは不要です。

@item Emacs 20.x
追加のパッケージは不要です。さらに BITMAP-MULE パッケージを使うと、白黒
のビットマップ画像をインライン表示することができます。@xref{Other
Requirements}。

@item XEmacs 21.x
APEL パッケージと @samp{gifsicle} プログラムが必要です (@pxref{Other
Requirements})。最も安定している最新の XEmacs 21.4 を使うことを推奨しま
す。

@item Emacs 19.34 (含 Mule 2.3)
APEL パッケージ、@samp{新しい custom} パッケージおよ
び @file{regexp-opt.el} モジュールが必要です。@xref{Other Requirements}。

@end table

@node You Need w3m
@section You Need w3m
@chapter w3m を使います: emacs-w3m が速いわけ

Emacs-w3m は外部コマンド w3m を web コンテンツを取得するためのバックエン
ドとして、または HTML の翻訳エンジンとして使用します。Emacs がそのような
仕事から解放されたので、高速な Emacs web ブラウザーと非同期動作を実現す
ることができました。あなたは最新の w3m コマンドをインストールしなければ
なりません。それは以下の場所で取得できます:

@uref{http://prdownloads.sourceforge.net/w3m/}

@node Other Requirements
@section Other Requirements
@chapter emacs-w3m を動作させるのに必要なもの


@node Index
@unnumbered 索引

@menu
* Concept Index::               概念索引
* Key Index::                   キーバインド索引
* Variable Index::              変数索引
* Function Index::              関数索引
@end menu

@node Concept Index
@unnumberedsec 概念索引
@printindex cp

@node Key Index
@unnumberedsec キーバインド索引
@printindex ky

@node Variable Index
@unnumberedsec 変数索引
@printindex vr

@node Function Index
@unnumberedsec 関数索引
@printindex fn

@summarycontents
@contents
@bye

@c Local Variables:
@c fill-column: 72
@c End:
